### ISSUE TITLE
Scroll bars should not be shown in the tab - the size should be exact

### ISSUE THREAD

**Issue by wywywywy** [zero01101/openOutpaint-webUI-extension#12]
**Describe the bug**
![image](https://user-images.githubusercontent.com/19997747/209587095-35a40c81-c8a2-4533-9656-043662d16976.png)

**To Reproduce**
1. Use Chrome latest
2. Scroll bars appear
3. Adjust window size, zoom level, etc, scroll bars still there

**Expected behavior**
Scroll bars should not be there, because the iframe size should be exact

**Desktop (please complete the following information):**

- Windows 11
- Chrome latest
- commit 115153091eb9ba79b83e2ae3d73886c9b62538f8

**Additional context**
Does not happen with Firefox.

I think Chrome handles sizing a bit differently.  If we look at the left/height/width/etc of the iframe from the dev console, we can (surprisingly) see some decimal numbers.

This below should be a good fix that works on both Chrome and Firefox.

```javascript
	const recalculate = () => {
		// If we are on the openoutpaint tab, recalculate
		if (tabEl.style.display !== "none") {
			frame.style.height = window.innerHeight + "px";
			const current = document.body.scrollHeight;
			const bb = frame.getBoundingClientRect();
			const iframeh = bb.height;
			const innerh = window.innerHeight;
			frame.style.height = `${Math.floor(iframeh + (innerh - current)) - 1}px`;
			frame.style.width = `${Math.floor(window.innerWidth) - 1}px`;
			frame.style.left = `${Math.floor(parseInt(frame.style.left, 10) - bb.x)}px`;
		}
	};
```

**Comment by zero01101** [comment]
huh, can't confirm locally on chrome 108.0.59whatever it claims to be up-to-date (win10x64), but it's definitely a reasonable and noninvasive enough fix that i'm pretty comfy with just dropping it in :) should be added in https://github.com/zero01101/openOutpaint-webUI-extension/commit/ab5b22ed74ad52cc29c951483db7f0a4248c2a16
