### ISSUE TITLE
register "send to outpaint" on additional tabs

### ISSUE THREAD

**Issue by vladmandic** [zero01101/openOutpaint-webUI-extension#20]
Currently this extension creates `Send to openOutpaint` button on **txt2img** and **img2img** tabs
Request is to have same button on **Extras** and **PNG info** tabs

One example case would be to generate image and save it and then later load it using **PNG info** and continue with outpainting.

**Comment by seijihariki** [comment]
Extras tab should be easy. PNG info... need to see, as all until now were gradio galleries.

**Comment by vladmandic** [comment]
silly workaround is to load using `PNG info` send to `img2img` to do inpaininting with nothing masked and then send to openOutpaint - you can see how silly that is :)

**Comment by seijihariki** [comment]
@vladmandic check testing branch

**Comment by vladmandic** [comment]
@seijihariki just tried it, works like a charm (both png info and extras tabs) - thanks!
