### ISSUE TITLE
UI Dropdown menus are not folding up

### ISSUE THREAD

**Issue by NanakoAC** [zero01101/openOutpaint-webUI-extension#23]
My openOutpaint menu looks like this
https://i.imgur.com/CrgvO5A.png

Running on chrome browser

I've figured out whats going on. The menu has a variety of dropdown submenus that you're supposed to click to expand
Prompts
Stable Diffusion Settings
Save/Upscaling
Debug Info

However, these are being rendered as permanantly expanded even when closed. All the content is rendered ontop of each other in the same spot
 If i click one to open it, the menus below it shift down to give it room, although those above in the list arent affected and will still render over it
Here's Stable Diffusion Settings and Prompts both expanded
https://i.imgur.com/qMFBbhO.png

They are mostly readable, so the program is useable, but this is still quite inconvenient

Great tool otherwise!

**Comment by zero01101** [comment]
hey, would you mind filling out this section of the bug report form? this feels like another extension issue  

---

**Environment (please complete the following information):**

- OS and Version: [e.g. iOS 15, win10x64 v22h2, palmOS 3]
- GPU: [e.g. GTX1660, RTX3090, RX750, Voodoo2]
- Browser and Version: [e.g. chrome 108, safari 16.1]
- Any browser extensions: [rationale: [microsoft editor chrome addon hates overmask](https://github.com/zero01101/openOutpaint/discussions/88#discussioncomment-4498341)]
- Commit of openOutpaint-webUI-extension: [e.g. 0217dec, https://github.com/zero01101/openOutpaint-webUI-extension/commit/342142952a63eddcb1cb5a1f18a9affc281e4526]
- Commit of A1111 webUI: [e.g. c5bdba2, https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5f1dfbbc959855fd90ba80c0c76301d2063772fa]
- How you interact with A1111 webUI: [e.g. local hardware, colab, cloud host like linode]

**Comment by seijihariki** [comment]
@NanakoAC Were you able to resolve your issue?

**Comment by NanakoAC** [comment]
no the issue is not resolved
Windows 10, Version	10.0.19044 Build 19044
GPU: Name	NVIDIA GeForce RTX 3090 Ti
Browser: Google Chrome | 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)
Extensions: Only one (dark reader. I tried disabling it, no change)

Not sure how to find those commits yet, but fairly recent
i use local hardware and google chrome

**Comment by zero01101** [comment]
>Browser: Google Chrome | 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)

_wow_ so that's a nearly 3-year-outdated build you're using there, uh, any chance you could update that to something a bit more modern, or try a different updated browser?
![image](https://user-images.githubusercontent.com/1649724/213817422-8f400924-47d4-4458-a42e-fab155fa1a4e.png)

**Comment by seijihariki** [comment]
Yeah... 3 years is quite a long time... Very surprised, actually, that openOutpaint managed to run at least okay at all.

**Comment by seijihariki** [comment]
Will be closing this issue for now as it seems to be an outdated browser version.
