### ISSUE TITLE
[Bug]: Tried to install openOutpaint extension, Receiving error messages (I'm a beginner)

### ISSUE THREAD

**Issue by fabstr1** [zero01101/openOutpaint-webUI-extension#26]
### What happened?

I have installed the extension, openOutpaint on Stable Diffusion by clicking on Extensions -> Available on the UI. I tried it, but I got two error messages one at the prompt and on in the UI. At the prompt, I have the message:

"Warning: Bad ui setting value: img2img/Mask mode/value: Draw mask; Default value "Inpaint masked" will be used instead.
Running on local URL: http://127.0.0.1:7860/"

The second message is from the UI, in the openOutpaint tab at the right side of the IP address, there is a yellow warning sign. When I click on it, a popup window is then shown this message:
"From 127.0.0.1:7869 The host is online, but the API seems to be disabled.
Have you run the webui with the flag '--api' or is the flag '--gradio-debug'
currently active?"

> 

### Steps to reproduce the problem

1. Open A1111 WebUI (Pin to Taskbar).ps1
2. Install and download the extension openOutpaint from the UI
3. Go to openOutpaint and see if there is a yellow warning sign to the right of the IP address and check your prompt for the error 
    message mentioned above.

### What should have happened?

I'm expecting that I would have no warning signs in either in the UI or in the prompt.

### Commit where the problem happens

0b8911d883118daa54f7735c5b753b5575d9f943

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Other

### Browser Extensions/Addons

Adblock for Youtube, Google translate, Tampermonkey, Return Youtube dislike, YCS youtube comment search

### AUTOMATIC1111 webUI Commandline Arguments

In overview, in AUTOMATIC1111 WEBUI menu, the following default command line arguments are listed:
--medvram --xformers.

### Additional information

I'm using Opera to access the UI, this was the default settings.

**Comment by seijihariki** [comment]
You need to use --api as a command line arg as well.

**Comment by fabstr1** [comment]
> 

Where, in A1111 Web UI Autoinstaller\stable-diffusion-webui\webui.bat ?

**Comment by seijihariki** [comment]
Yes.

**Comment by zero01101** [comment]
assuming you're using https://github.com/EmpireMediaScience/A1111-Web-UI-Installer, you'd add ` --api` in here after whatever else is already in there: 
![image](https://user-images.githubusercontent.com/1649724/212491232-1c565e8f-9108-4bd4-a5ae-25fef9651379.png)

**Comment by seijihariki** [comment]
Didn't even know that existed. Good one!

**Comment by fabstr1** [comment]
Thanks, it worked
