### ISSUE TITLE
[Bug]: styles are not applying correctly

### ISSUE THREAD

**Issue by xirishpvp** [zero01101/openOutpaint-webUI-extension#27]
### What happened?

so i was trying to recreate some images and noticed that the style wasn't applying how it does when i do the style manually

example
![2023-01-15 06 27 23 openOutpaint image](https://user-images.githubusercontent.com/105259880/212526353-bc32ea7b-062f-4b2c-8b21-ab89d42c02f7.png)
the first image was
"(a young woman:1.0)(dark red hair:1.0)((yellow:1.15)eyes:1.0)((dark red:1.1)lips:1.0)(big boobs:0.6)(thick thighs:1.12)(wearing black plate armor:1.0)(face in focus:1.25)(head and shoulders portrait:1.0)(anime:1.2)(greg rutkowski:1.2)(vibrant colors:1.0)(matte:1.0)(graffiti style:1.0)(intricately detailed:1.0)(volumetric lighting:1.0)"
with no style

second image was 
"(a young woman:1.0)(dark red hair:1.0)((yellow:1.15)eyes:1.0)((dark red:1.1)lips:1.0)(big boobs:0.6)(thick thighs:1.12)(wearing black plate armor:1.0)(face in focus:1.25)(head and shoulders portrait:1.0)"
with "(greg rutkowski:1.2)(vibrant colors:1.0)(matte:1.0)(graffiti style:1.0)(intricately detailed:1.0)(volumetric lighting:1.0)" as style

third image was 
"(a young woman:1.0)(dark red hair:1.0)((yellow:1.15)eyes:1.0)((dark red:1.1)lips:1.0)(big boobs:0.6)(thick thighs:1.12)(wearing black plate armor:1.0)(face in focus:1.25)(head and shoulders portrait:1.0)"
with no style or (greg rutkowski:1.2)(vibrant colors:1.0)(matte:1.0)(graffiti style:1.0)(intricately detailed:1.0)(volumetric lighting:1.0)"

### Steps to reproduce the problem

1. Go to open out paint
2. chose a style and use it to compare to an image
3. compare with if you had used the style manualy for an image

### What should have happened?

not accurate image generation from using styles to fill header text to a prompt

1st image is with full prompt no style
2nd is with style
3rd is missing what style should have added to 1
![2023-01-15 06 27 23 openOutpaint image](https://user-images.githubusercontent.com/105259880/212526628-79a17d4c-9478-4c17-a9b9-4f9ed8fc19db.png)

### Commit where the problem happens

https://github.com/zero01101/openOutpaint-webUI-extension/commit/b0603fba8bb46a21b6c37e02104a3df3ec242a44

### What platforms do you use to access openOutpaint?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

ghostery, duckduckgo privacy essentials, tree style tab, adblocker ultimate, plasma integration, read aloud

### AUTOMATIC1111 webUI Commandline Arguments

--api --medvram --opt-split-attention --precision full --no-half

### Additional information

bit new to commenting so if you need any more info feel free to comment to give me feed back
also im using a custom blend model so you might get different results from the images

**Comment by seijihariki** [comment]
So... the thing about styles is that we use the AUTOMATIC1111's API style input, so we are not really applying the styles, but asking AUTOMATIC1111's webui to apply them for us, and it seems the webui does apply them okay. These were generated with the same settings, seed and styles applied:

![image](https://user-images.githubusercontent.com/7552751/212541664-1f227d8c-a06f-403f-8d15-91bbef6987ee.png)
![image](https://user-images.githubusercontent.com/7552751/212541671-3531debd-45ca-4ba2-97d9-ea7b9abbef44.png)

This is the request sent to the UI. As you can see, we just send style names, and the webui itself applies them:

![image](https://user-images.githubusercontent.com/7552751/212541762-263d7841-edd3-4a55-968d-33fb36bcf6d3.png)

**Comment by seijihariki** [comment]
So if styles are not being applied correctly, it would be a webui issue (and a consistent issue with the base txt2img tab style application)

**Comment by zero01101** [comment]
also just to further ensure styles still work as expected in openOutpaint, i've got a style that's just the default prompt/negative prompt which works a-ok with completely empty prompt input fields :/  

removing #bug, adding #external and #wontfix

![style](https://user-images.githubusercontent.com/1649724/212555445-5f95c797-5408-4b60-958a-116c0a0894d5.gif)
