### ISSUE TITLE
[Bug]: NOT A BUG - I want to know how to change how many iterations it does. Seems to be on 4.

### ISSUE THREAD

**Issue by githubUser01946** [zero01101/openOutpaint-webUI-extension#32]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

Despite having `iterations:2` on the openOutpaint menu on the left of the canvas it still does a minimum of 4. Also when pressing the + button to do more iterations, it again does 4.

Is there anyway to change this so that I can choose to do 5/6 or whatever to start with and any further iterations to be chosen?

I havent posted in feature request as I assume that the feature I am looking for already exists somewhere.

### Steps to reproduce the problem

n/a

### What should have happened?

n/a

### Commit where the problem happens

05052c05d87753cfc2f65017828fdcc1b8a83cce

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Browser Extensions/Addons

n/a

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --medvram --api

**Comment by zero01101** [comment]
just out of curiosity, you've got the batch size set to 1 as well, correct?  batch size determines how many images are rendered in a single "batch" process, and iterations is how many times to run a batch.  

i don't exactly use edge... ever... with openOutpaint, but it definitely works as expected here; if you push f12, open the "network" tab, and look at the payload subtab for the POST request to txt2img/img2img - what's passed for the `batch_size` and `n_iter` parameters?  

this is 4x images via 2x batch, 2x iterations:  

![image](https://user-images.githubusercontent.com/1649724/213816852-012d32b2-5203-489b-81f1-66887af56ef4.png)

this is 3x images via 3x batch, 1x iteration:

![image](https://user-images.githubusercontent.com/1649724/213816974-02af4b3b-3735-49f5-abf8-c3df7998ae60.png)

this is 6x images via 2x batch, 3x iteration in the extension 

![image](https://user-images.githubusercontent.com/1649724/213817090-a30680e6-2007-477b-9c2b-9f8f7b45f6ec.png)

so it definitely seems to be working in both standalone and extension as far as i can test on my machine :/

**Comment by githubUser01946** [comment]
> you're just leaving them at their defaults of 2

This is the issue. Thanks :)

I knew it wasnt a Bug but didnt have an option other than that to choose.
