### ISSUE TITLE
[Feature Request]:Remove the refresh button 

### ISSUE THREAD

**Issue by MILKHEADSET** [zero01101/openOutpaint-webUI-extension#33]
### Is your feature request related to a problem? Please describe.

That refresh button is in just the right place to accidentally hit it when you are zooming in and out a lot and cant see the entirety of the image to image or dream box. I have lost more than a half an hour of work to that button multiple times, and the last time I just about cried. Open outpaint is great, and I love the utility of the integrated extension, but I have uninstalled the extension and will be using the separate server bat until that refresh button is removed. It's cost me too much work too many times. 

### Describe the solution you'd like

Removal of the refresh button. 

### Proposed workflow

I don't want the feature accessible at all. If I need a hard refresh, I will use CTRL R. If that refresh button is absolutely necessary, it needs to be somewhere that is _not_ accessible on the canvas, and it needs to have protection against accidental clicks. There should at the very least be a popup asking if you really want to reload the page if you are insistent on having it directly accessible from the canvas. 

### Describe alternatives you've considered

Using the .bat server from now on.

**Comment by zero01101** [comment]
sorry about the lost work :( that definitely sucks 

if it's any consolation, the refresh button now has a `confirm()` dialog before refreshing as of https://github.com/zero01101/openOutpaint-webUI-extension/commit/3ebc1812ecdfd3578852dfb09532ddc53a3728a2
