### ISSUE TITLE
[Feature Request]: Automatic zoom on sendToOpenOutpaint

### ISSUE THREAD

**Issue by Baughn** [zero01101/openOutpaint-webUI-extension#34]
### Is your feature request related to a problem? Please describe.

I commonly start outpainting sessions from the txt2img or img2img tabs of A1111, often used at fairly high resolution. When I click Send to OpenOutpaint, this leads to the image being larger than the visible canvas.

### Describe the solution you'd like

Either automatically zoom out to fit the image in the viewport, or (perhaps better) make the default zoom value small enough to display the entire canvas.

### Proposed workflow

1. Go to OpenOutpaint
2. Entire canvas should be visible at startup.

### Describe alternatives you've considered

Zooming out on the browser tab works, but the text gets hard to read.

**Comment by seijihariki** [comment]
We can make default canvas resolution smaller (still changeable via settings) and auto zoom to fit canvas on boot. Would that work?

**Comment by Baughn** [comment]
Well... not really, to be honest? The default canvas size is already pretty small. I usually end up expanding it.

**Comment by githubUser01946** [comment]
This would be nice CTRL+- lets us zoom out but as mentioned, text becomes too small to read.

**Comment by seijihariki** [comment]
@Baughn Sorry for taking so long. See if this seems okay.

**Comment by seijihariki** [comment]
Will be closing as implemented, if there are any issues with the current implementation, please send a message here and we will reopen it.
