### ISSUE TITLE
[Bug]: Popup to change model opens on app start

### ISSUE THREAD

**Issue by muunkky** [zero01101/openOutpaint-webUI-extension#39]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

The extension suggests that you change to an inpainting model (which is good). However it does it as soon as you open the app, so even if you have no intention of using openoutpaint, you still have to click "cancel" on the popup. 9 times out of 10, I hit space or enter by accident and it changes my model.

### Steps to reproduce the problem

Open automatic1111 interface
See popup

### What should have happened?

Open automatic1111
Go to openoutpaint tab
See popup

### Commit where the problem happens

a0e7608d06cca21e209b896561ec1dbec46fdaa0

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

happens in incognito with no extensions running

### AUTOMATIC1111 webUI Commandline Arguments

--autolaunch --medvram --xformers --vae-path C:\Users\username\stable-diffusion-webui\models\Stable-diffusion\sd-v1-5.vae.pt --medvram --api --cors-allow-origins http://localhost:5173,https://127.0.0.1:7860/,https://127.0.0.1:3456

**Comment by seijihariki** [comment]
Makes sense. Will give this a look. We have been a bit slow due to life stuff recently, but use ability stuff is important.  I think this would actually be fixed by https://github.com/zero01101/openOutpaint/issues/151, so I will be tackling that issue to solve this one as well.

**Comment by seijihariki** [comment]
It should be solved on latest. Please give it a look.

**Comment by seijihariki** [comment]
Closing for now. If you have any issues with the current implementation, please send a message here and we will reopen the issue.
