### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Marcusgeorgiadis** [zero01101/openOutpaint-webUI-extension#40]
### Is your feature request related to a problem? Please describe.

no denoise setting

### Describe the solution you'd like

denoise setting

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...
denoise setting

### Describe alternatives you've considered

n/a

**Comment by seijihariki** [comment]
There is denoise input for img2img. Is it another denoising input you are asking for?

**Comment by seijihariki** [comment]
Will be closing this issue for now, for lack of information to properly address the issue.
