### ISSUE TITLE
[Bug]: Extension won't "activate"?

### ISSUE THREAD

**Issue by jwvanderbeck** [zero01101/openOutpaint-webUI-extension#42]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

I don't know what I am doing wrong here, but every time I try to install this extension everything seems to install correctly, but when I restart a1111 there is no new openOutpaint tab, and if I go to extensions it shows the extension installed but unchecked which I think means disabled? Nothing I do seems to enabled it.

I have --api set and the API seems to work through some quick testing.

### Steps to reproduce the problem

1. enable --api, restart webui
2. install openoutpaint, restart webui
3. look for outpaint tab

### What should have happened?

I expect to see the new openOutpaint tab

### Commit where the problem happens

989a3fa0 

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

1passwoird, uBlock origin, Video downloader professional

### AUTOMATIC1111 webUI Commandline Arguments

--api --medvram

**Comment by jwvanderbeck** [comment]
Not sure what happened or change but it literally just randomly started working.  Sorry to bother you.

**Comment by zero01101** [comment]
lol yeah terribly sorry; if you can somehow reproduce this i'd love to know how because that, uh, shouldn't happen?
