### ISSUE TITLE
[Bug]: Render progress is split on multiple lines

### ISSUE THREAD

**Issue by prodigy1** [zero01101/openOutpaint-webUI-extension#44]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

The progress bar is split on multiple lines after installing the extension. I found out it's open outpaint because I disabled all extensions and enabled one after the other. For me it looks like this:
![image](https://i.ibb.co/mb4QXqM/2023-03-10-17-01-53.png)

After removing all content from all .py files from the open outpaint extension the wrong display is gone as well.

I found out it is the `run('git submodule update')` command.

By appending `live=True` to the arguments of `run()` - at least for me - the problem is gone.

I don't know whether this is an issue of open outpaint or at the core lies at automatic1111. But adding live=True fixed it for me. Internally the `run()` method then no longer fiddles with output streams and encodings. I guess this is the actual core of the issue.

For me this fixed the problem:
```
diff --git a/scripts/main.py b/scripts/main.py
index 7f9b967..7ed2d38 100644
--- a/scripts/main.py
+++ b/scripts/main.py
@@ -53,7 +53,7 @@ def update_app():
     git = os.environ.get('GIT', "git")
     # print(scripts.basedir)
     run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1]) +
-        '" submodule update --init --recursive --remote')
+        '" submodule update --init --recursive --remote', live=True)
 
 
 def add_tab():
```

### Steps to reproduce the problem

1. Install the extension
2. Render a picture
3. Look at the progressbar

### What should have happened?

The progress bar displays as normal:
![image](https://i.ibb.co/f4JF7mT/2023-03-10-17-05-01.png)

### Commit where the problem happens

989a3fa0e8111f444e58cc719906b61da921d21c

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Other (please list in additional information)

### Browser Extensions/Addons

not applicable

### AUTOMATIC1111 webUI Commandline Arguments

--listen --xformers --opt-channelslast --no-half --no-half-vae --precision full --api --enable-insecure-extension-access --cors-allow-origins=https://mydomain/

**Comment by zero01101** [comment]
confirmed and many thanks, i'd WONDERED when that started happening and why but never would have thought it was my own fault  
![lil bad pokerface](https://user-images.githubusercontent.com/1649724/224438265-9f0261a8-6190-428f-a453-00aaa5fc9151.png)  
fixed in https://github.com/zero01101/openOutpaint-webUI-extension/commit/3019f91477b912b0b635da474ada0fbc939f7d1f with my thanks for your debugging :D
