### ISSUE TITLE
[Bug]: Button "send to openOutpaint" dont work.

### ISSUE THREAD

**Issue by amokiller** [zero01101/openOutpaint-webUI-extension#48]
### What happened?

(First sorry im not english)
The button "send to openOutpaint" dont work, does nothing, but in Chrome console show errors (attachment image)
Only work from PNGinfo, but only send picture no other parameters (maybe this is intentional)

im use Automatic1111 and extension, last build of both

![image](https://user-images.githubusercontent.com/1351789/229488910-ae6e2389-247e-4cd3-ae36-e72d68ebc9b7.png)

### Steps to reproduce the problem

1. Text to image and generate something
2.  Press Button send to openOutPaint

### What should have happened?

Send img (and parameters?) to openOutpaint

### Commit where the problem happens

version 566a8a53

### What platforms do you use to access openOutpaint?

Windows, Linux, Other/Cloud

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Browser Extensions/Addons

![image](https://user-images.githubusercontent.com/1351789/229490598-25c0bc6b-122e-43a3-853d-15a0f66e6d4e.png)

### AUTOMATIC1111 webUI Commandline Arguments

--api --opt-split-attention --no-half-vae --disable-safe-unpickle  --xformers --autolaunch  --theme dark

### Additional information

Tested in multiple combinations of:

Windows 10, Ubuntu, Google colab
Chrome, firefox

**Comment by zero01101** [comment]
hey, so commit https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53 was pushed to handle this against the latest webUI/gradio updates - there's definitely some issues with colabs and webUI it seems, particularly with the txt2img API endpoint which breaks openOutpaint, but the buttons work as expected against the most recent webUI commits on both windows and ubuntu...  is your webUI on the most up-to-date release (post the gradio version bump)?  

(moved issue to extension repo)

**Comment by amokiller** [comment]
@zero01101 
im not sure . In footer no show version. Commit its blank

![image](https://user-images.githubusercontent.com/1351789/230324750-7e3d9672-b1e1-45d0-9a17-b1ce8df73b14.png)

How can I know what version is installed?

**Comment by zero01101** [comment]
hey, sorry for the delay; in your command prompt/terminal go to your webUI directory and type in `git rev-parse HEAD` which should show the commit hash but yeah, that's... odd that it's not there...

**Comment by webbigdata-jp** [comment]
Hi, thanks for the great extension.
I had the same error and solved it by reading this issue. 

Reference information.
I'm using it via ReverseProxy, but the latest AUTOMATIC1111/stable-diffusion-webui gave me a Websocket related error and could not generate images.

Therefore, I use AUTOMATIC1111 3/24.
280ed8f00fde0ece026339acdd42888ac4dc3167

This is the version before the changes occurred in Gradio, so I had to revert OpenOutPaint to before the changes below.
https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53
