### ISSUE TITLE
[Bug]: `Hires fix` does not appear to work with `dream` while containing part of an existing image stamp

### ISSUE THREAD

**Issue by zixaphir** [zero01101/openOutpaint-webUI-extension#53]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

I am not entirely sure if this is a feature request or a bug report, so I'm going to be treating is as a bug report. I enabled `hires fix` because outpainting from my 1024x1024 image was generating bad anatomy (extra legs, legs coming out of surfaces they should not have, etc) thinking that it would help. Instead, it just continued generating at the same resolution without the upscale and second pass. I thought maybe I was doing something incorrectly, so I tried separating resolution from cursor size, using a smaller resolution to `dream` with. This was also futile. 

I read through the documentation to see if this was a known limitation or known issue, but found nothing about it. I read further into how the `hires fix` portion was intended to use, and attempted with both lying to `hires fix` and not lying to it. Lying to it seemed to be what I was attempting to do previously by decoupling synchronization of the resolution from the cursor size, but I was trying to figure out anything that would have passed as a workaround. 

Eventually I settled on just downscaling my original image, outpainting the lower half of my character, then upscaling from the Extras tab (obviously not part of the extension), using photoshop to restore the hires sections, and then inpainting the lower half with the sample count and denoising level I would have used for `hires fix`, which is not unworkable, but just a bit more tedious.

Additionally, I attempted to `dream` outside of the original image bounds, which produced a result incongruous to the image I wished to outpaint (as expected), but successfully applied `hires fix`.

### Steps to reproduce the problem

1. Stamp your source image for outpainting
2. Select the `dream` tool and set your desired settings and enable `Apply Txt2img HRfix`
3. `Dream` to outpaint an extension of the image in a single direction (perhaps other directions, but I did not test this)

### What should have happened?

The txt2img `hires, fix` should be applied to the portion of the outpainting, regardless if it contains existing image data.

### Commit where the problem happens

5e84d6d5 (Mon Apr 10 23:01:41 2023)

### What platforms do you use to access openOutpaint?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

![image](https://user-images.githubusercontent.com/438570/235059297-5061bfa0-0287-4a1c-96c4-3a75e5720de3.png)

### AUTOMATIC1111 webUI Commandline Arguments

```export COMMANDLINE_ARGS=" --no-half-vae --no-gradio-queue --xformers --api"```

**Comment by zero01101** [comment]
hey, sorry for the delay; so unfortunately this is kind of neither a bug report NOR a feature request; the reason the tool is called "dream" and not txt2img is because it dynamically jumps between txt2img and img2img functionality depending on the contextual data in the reticle - if it's entirely empty, it's a txt2img operation and HRfix can be applied, but as soon as there's existing image data, HRfix will do nothing as it's strictly a txt2img operation within A1111 webUI currently.

**Comment by zixaphir** [comment]
Ah. This is one of those things where implementing it would require writing their own implementation of `hires fix`.
