### ISSUE TITLE
Colab: The host is online, but the API seems to be disabled

### ISSUE THREAD

**Issue by Lesteriax** [zero01101/openOutpaint-webUI-extension#6]
**Describe the bug**
I'm using automatic1111 on Colab and running the extension is prompting me with the following:
The host is online, but the API seems to be disabled. Have you run the webui with the flag --api?

I have set up the webui command argument with --api but still getting the same message.

**Screenshots**
![image](https://user-images.githubusercontent.com/95050087/209427685-314ee10b-709b-458c-8f14-7172aa2b0ea9.png)

**Comment by seijihariki** [comment]
Give this fix a look. I just fixed my best guess on the problem.

**Comment by Cyphco** [comment]
Might have found a solution, ran into the same issue but after removing the --gradio-debug flag it started to work, something there might interfere.

**Comment by seijihariki** [comment]
Can confirm that adding `--gradio-debug` disables any custom API routes, thus breaking openOutpaint.

![image](https://user-images.githubusercontent.com/7552751/209446522-33db8c32-b51b-4720-841e-298ae5ef475c.png)

@zero01101 We should add this to the readme/quickstart.

**Comment by zero01101** [comment]
_fascinating_; yeah, will definitely add mention of that :|

**Comment by zero01101** [comment]
also updated the js alert text as well, probably handy for anyone just running into that i figure

**Comment by seijihariki** [comment]
As this seems to be solved and documentation has been mostly updated, will be closing this issue.
