### ISSUE TITLE
[Bug]: Error when starting Auto1111 webui

### ISSUE THREAD

**Issue by Gushousekai195** [zero01101/openOutpaint-webUI-extension#61]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

```
error: Your local changes to the following files would be overwritten by checkout:
        js/index.js
Please commit your changes or stash them before you switch branches.
Aborting
fatal: Unable to checkout 'e0c9ab0c687397257fd4b3beeaeeaa2a69186b6c' in submodule path 'app'
Loading VAE weights specified in settings: C:\Users\mattb\stable-diffusion-webui\models\VAE\WD-KL-F8-Anime2.vae.pt
error: Your local changes to the following files would be overwritten by checkout:
        js/index.js
Please commit your changes or stash them before you switch branches.
Aborting
fatal: Unable to checkout 'e0c9ab0c687397257fd4b3beeaeeaa2a69186b6c' in submodule path 'app'
Error executing callback ui_tabs_callback for C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py
Traceback (most recent call last):
  File "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py", line 64, in add_tab
    update_app()
  File "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py", line 55, in update_app
    run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1]) +
  File "C:\Users\mattb\stable-diffusion-webui\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Error running command.
Command: "git" -C "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattb\stable-diffusion-webui\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py", line 66, in add_tab
    update_app()
  File "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py", line 55, in update_app
    run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1]) +
  File "C:\Users\mattb\stable-diffusion-webui\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Error running command.
Command: "git" -C "C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 1
```

### Steps to reproduce the problem

1. Have OpenOutpaint installed.
2. Start the Auto1111 webui.

### What should have happened?

The error above should not have happened

### Commit where the problem happens

f8b28838

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

OneButtonPrompt | https://github.com/AIrjen/OneButtonPrompt | main | bd1318d8 | Sun Jul 9 14:02:27 2023 | unknown
-- | -- | -- | -- | -- | --
a1111-mini-paint | https://github.com/0Tick/a1111-mini-paint | main | 8545c9cd | Mon Jun 12 14:04:04 2023 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris | main | 8e97bf54 | Sun Jul 9 07:44:58 2023 | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete | main | 737b6973 | Sat Jul 8 16:03:44 2023 | unknown
openOutpaint-webUI-extension | https://github.com/zero01101/openOutpaint-webUI-extension | main | f8b28838 | Sun Jul 9 13:42:16 2023 | unknown
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts.git | main | fa49646b | Sat Jul 8 16:27:15 2023 | unknown
sd-webui-3d-open-pose-editor | https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git | main | f2d5aac5 | Sat Apr 15 13:21:06 2023 | unknown
sd-webui-aspect-ratio-helper | https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git | main | 99fcf9b0 | Sun Jun 4 15:39:07 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 07bed6cc | Sat Jul 8 20:54:01 2023 | unknown
sd-webui-e621-prompt | https://github.com/nochnoe/sd-webui-e621-prompt | main | 8d000042 | Thu Jun 15 16:20:48 2023 | unknown
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git | main | e4735315 | Sat Jul 8 03:16:01 2023 | unknown
stable-diffusion-webui-images-browser | https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git | main | b2f6e4cb | Thu Jun 8 08:11:43 2023 | unknown
stable-diffusion-webui-promptgen | https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen.git | master | 84e58b5d | Fri Jan 20 11:15:12 2023 | unknown
stable-diffusion-webui-rembg | https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git | master | 3d9eedbb | Sun Jun 4 13:35:24 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | c99f382b | Tue Jun 13 04:29:35 2023 | unknown
webui-alternative-init-noise

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --no-half-vae --no-half --precision full --api --opt-sdp-no-mem-attention --disable-nan-check --no-gradio-queue --ngrok

**Comment by zero01101** [comment]
that indicates you've made some kind of local change to the `index.js` file in the submodule at some point - open a command prompt and navigate to `C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension` and execute `git stash`

**Comment by Gushousekai195** [comment]
> that indicates you've made some kind of local change to the `index.js` file in the submodule at some point - open a command prompt and navigate to `C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension` and execute `git stash`, and the submodule should update accordingly on next launch.
> 
> you could alternatively just delete the `C:\Users\mattb\stable-diffusion-webui\extensions\openOutpaint-webUI-extension` directory entirely and reinstall from the extensions tab

Didn't work. It said "No local changes to be saved." Error persists.

**Comment by zero01101** [comment]
hm, the error it states regarding index.js is quite explicit in that it's what's causing the update too fail, but I'm not sure what to tell you regarding git stash. regardless, simply deleting the extension entirely, restarting A1111, and reinstalling from the extensions tab will fix it
