### ISSUE TITLE
[Bug]: Send To buttons missing on upstream A1111 dev

### ISSUE THREAD

**Issue by Kadah** [zero01101/openOutpaint-webUI-extension#63]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

Upstream changes in A1111 dev breaks the custom Sent To buttons.

### Steps to reproduce the problem

1. Switch to dev branch on A1111
2. Note missing Sent To buttons

### What should have happened?

Have Sent To Outpainter buttons.

### Commit where the problem happens

https://github.com/zero01101/openOutpaint-webUI-extension/commit/726652f23de7725d51e3296c97517849e9405fa6

### What platforms do you use to access openOutpaint?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

Non active on webui

### AUTOMATIC1111 webUI Commandline Arguments

--api --cors-allow-origins=http://127.0.0.1:7860,http://127.0.0.1:3456

### Additional information

Also getting no canvas on the extension's tab, but also getting that when running to the release branch of A1111, so possibly unrelated. Still testing.

**Comment by zero01101** [comment]
missing buttons confirmed and being worked on for A1111 merge to main

>Also getting no canvas on the extension's tab

yeah that feels like a browser privacy thing potentially; that's generally what causes that...

**Comment by Kadah** [comment]
> missing buttons confirmed and being worked on for A1111 merge to main

Any chance of getting that in a branch or fix that checks A111 version? 1.6 is in RC now.

**Comment by zero01101** [comment]
hey, terribly sorry for the delay; i meant to push this to a test/dev branch but [excuse] :/ anyhoo, it's on main now

**Comment by Kadah** [comment]
Can confirm fixed. Thanks!
