### ISSUE TITLE
Ability to zoom and pan the image

### ISSUE THREAD

**Issue by cibernicola** [zero01101/openOutpaint-webUI-extension#9]
First of all: super interesting this version of outpainting :)

On a usability level I think it would be very interesting to be able to zoom in and zoom out to the image, but only to the image as well as to move it on the canvas allowing the rest of the graphic environment not to be affected.

**Comment by seijihariki** [comment]
All camera funcions (zoom and pan) are done with the control key (Ctrl + middle mouse and drag), (Ctrl + scroll). Is this you are talking about?

**Comment by w84death** [comment]
Not everyone have a middle button. I'm voting for just a RMB for panning.

**Comment by seijihariki** [comment]
We are discussing alternatives to this as well, on https://github.com/zero01101/openOutpaint/issues/116. We can't really simply RMB as quick RMB drags would also be counted as clicks, which would just erase whatever is under them on some tools.

@w84death, I will be quoting you there for now, we can continue input discussions in that issue!

**Comment by cibernicola** [comment]
> All camera funcions (zoom and pan) are done with the control key (Ctrl + middle mouse and drag), (Ctrl + scroll). Is this you are talking about?

Ouch, sorry, didn't see that. Yup! That's exactly what I mean. Thanks!

**Comment by seijihariki** [comment]
Ok! This seems to be solved for now! We will continue to discuss input on the other issue.

Will be closing this for now!
